### PR TITLE
bz#1288608 - fix memory regions with unknown types marked available

### PR DESCRIPTION
**Pull request by kellinm**
This is a series of patches to address memory regions being marked available if they have unknown types.

### CODE REVIEW

**Comment by vathpela** [comment]
For rhel-7.3 this isn't going to work - it really needs to be a /single/ commit that has the bz# referenced properly.  The best thing to do is just apply these to a temporary branch based on rhel-7.3, diff rhel-7.3 against it, /apply that diff as a patch to rhel-7.3 , and commit the difference with a new log that includes the bz number and a list of the original commits.

Otherwise the "git push" bot is gonna go nuts.

**Comment by vathpela** [comment]
Er... it's probably easier just to cherrypick them all onto the rhel-7.3 branch, "rebase -i" and "fold" them together, and then "reword" the top one, and then just right a new commit message.

Dunno what I was thinking above.

**Comment by kellinm** [comment]
@vathpela - re-tagged these with cherry picks and the rhbz#.

**Comment by kellinm** [comment]
This is on the rhel-7.3 branch as of build 2.02-0.34

**Pull request closed without merging**
