### PR TITLE
SUSE changes for btrfs boot to snapshot for Fedora

### PR DESCRIPTION
**Pull request by Conan-Kudo**
This PR has the patch series for Btrfs boot to snapshot functionality developed by SUSE (with a change by @dustymabe to fix grubby incompatibility).

The patches come from [SUSE's OBS project for grub2](https://build.opensuse.org/package/show/Base:System/grub2?rev=270), and the authors + dates are divined from the OBS package changelog. Where real commit messages do not exist, the names of the patches are used instead.

There are a couple of patches related to `grub2-once`, which we don't have in Fedora, as well as an additional grub2 plugin script for snapper, which cannot be applied here (it's a packaging thing). These have been omitted, obviously, but can be viewed from the OBS project.

### CODE REVIEW

**Comment by dustymabe** [comment]
Thanks @Conan-Kudo!

**Comment by Conan-Kudo** [comment]
@vathpela, @dustymabe: If a Fedora 26 branch is desired as well, let me know and I can make a PR for F26, too.

**Comment by dustymabe** [comment]
hey @vathpela, do you mind taking a look :)

**Comment by Conan-Kudo** [comment]
@vathpela @dustymabe I've rebased the patch series on current `fedora-27` branch.

**Comment by dustymabe** [comment]
hey @vathpela - can you take a look at this?

**Comment by Conan-Kudo** [comment]
@vathpela @dustymabe I've rebased the patch set against the current `fedora-27` branch and pulled in the latest patch set from SUSE.

**Comment by vathpela** [comment]
I've pulled this in to my local fedora-27 tree; I'll push it there once I fix some rebase issues on my end.

**Pull request closed without merging**
